### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by kevinburke** [amaxwell/tlutility#118]
I'm attempting to install the "enumitem" package which I can see here: https://ctan.org/pkg/enumitem?lang=en

When I try to refresh the list of packages in the window, nothing happens - the only packages I can see are ones that I already have installed.

The "Log Window" says:

```
2021-09-15 03:02:45 +0000 Notice -[TLMLoadDatabaseOperation _dumpDatabaseAtURL:asPropertyList:][77752]	Parse error:     all_packages, index_map = packages_from_tlpdb(flat_tlpdb, options.allow_partial)
  File "/private/var/folders/s1/909yt58s4wj8h_7v7frr8rkm0000gn/T/AppTranslocation/3320123E-FC82-4C87-A6F7-8E78AF7B4B91/d/TeX Live Utility.app/Contents/MacOS/parse_tlpdb.py", line 242, in packages_from_tlpdb
    index_map[package.name] = package_index
AttributeError: 'NoneType' object has no attribute 'name'
```

I'm running Mac Catalina 10.15.7. I downloaded BasicTex today from tug.org. I'm not sure which version of Python is running, but if I type `python --version` at the command line I get `Python 3.8.0`.

**Comment by amaxwell** [comment]
I suggest trying again, and hopefully it's a transient error in a partial database. If that doesn't work, I'l need more log context to see if installing the package failed and which parsing step this was.

**Comment by kevinburke** [comment]
I tried a few times and got this error every time. It happens when I hit the "refresh" button next to the URL bar. The list of packages never updates to include any packages that I don't already have installed on my device.

**Comment by amaxwell** [comment]
I just downloaded and installed BasicTeX, and was able to install enumitem with no problems. I'd suggest trying another mirror, but if that doesn't work, post the full log output or email it to me at <amaxwell at mac dot com>.

**Comment by kevinburke** [comment]
Here's the full log, I get this output with any mirror that I try. https://gist.github.com/kevinburke/52979d3ec3bee4aee4bf485aaa379233

Here's the context for the NPE - `package` is None so `package.name` throws an error. It seems possible to achieve this if you hit an empty line before you reassign `package` from its initial value of `None`. I tried to add more print statements but Mac won't let me edit the Python file. 

```python
def packages_from_tlpdb(flat_tlpdb, allow_partial=False):
    """Creates a list of TLPackage objects from the given file-like object.
    
    Arguments:
    flat_tlpdb -- A file or file-like object, open for reading
    allow_partial -- Pass True if you want to return partial data after an error;
    useful in case of a partial tlpdb download. Default is to raise an exception.
    
    Returns:
    A list of TLPackage objects
    
    """            
    
    package = None
    package_index = 0
    all_packages = []
    index_map = {}
    last_key = None
    last_arch = None

    for line_idx, line in enumerate(flat_tlpdb):
    
        # seems to be absent in TL 2020 (not in stderr?)
        if line_idx == 0 and line.startswith("location-url\t"):
            TLPackage.mirror = line[len("location-url\t"):].strip()
            continue
            
        # comment lines; supported, but not currently used
        if line.startswith("#"):
            continue
                
        line = line.strip("\r\n")
    
        if len(line) == 0:
            all_packages.append(package)
            index_map[package.name] = package_index
            
            package_index += 1
            package = None
            last_key = None
            last_arch = None

```

**Comment by kevinburke** [comment]
I added some more print line debugging and ran the program again:

```
            try:
                index_map[package.name] = package_index
            except Exception:
                textfile = open("/tmp/log.txt", "w")
                textfile.write("attempting to assign to None package on line {}, package_index {}\n".format(line_idx, package_index))
                textfile.write("\n\n")
                textfile.write(flat_tlpdb)
                textfile.write("\n")
                textfile.close()
                raise
```

This writes to the log file:

```
attempting to assign to None package on line 0, package_index 0


```

I.e. it appears to be parsing an empty file. I can reproduce this with every mirror. If I use `curl` at the command line, the tpldb file for every mirror loads with no issues.

**Comment by amaxwell** [comment]
Very odd, because this did not happen for me with the rit.edu server. Do you have any software that would block the download? I guess I could check for an empty file, but this is the first time I've seen this problem.

You could also try running the script on a manually downloaded tlpdb. Note that TLU is using `/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python`.

**Comment by kevinburke** [comment]
When I run it with a file on disk it writes with no problems.

Earlier in the output I see a "needs root permission to write" message. Is it possible that the tpldb file is trying to download to that location, failing with a permission error, and then passing an empty string to parse_tpldb.py ?

**Comment by amaxwell** [comment]
Yeah, it's being passed an empty file (well, empty pipe, in this case). Looking at the code, it executes something like

`tlmgr --repository https://mirrors.rit.edu/CTAN/systems/texlive/tlnet dump-tlpdb --remote | parse_tlpdb.py-o /tmp/tlpdb.plist -f plist`

I'd forgotten that the actual download is happening inside tlmgr, which makes me wonder if there's a proxy screwing things up, or if your system is blocking downloads from the perl libraries.

The first download (of a partial tlpdb) happens using Cocoa, so I can just get a few kB to check the version number, rather than downloading a multi-megabyte file. This will access proxy settings differently than tlmgr, which relies on an environment variable being set (I try to read preferences for this, but it's not set in your case).

The root permission check is just to see if /usr/local/texlive is root-owned or user-owned. I don't want my code to run as root unless absolutely necessary, but most users don't bother to change ownership of /usr/local/texlive.

**Comment by amaxwell** [comment]
Did you figure out the problem? I'd like to know if there's anything I can do to improve this.
