### ISSUE TITLE
System python2 deprecated on macOS Monterey, will be removed in 10.16

### ISSUE THREAD

**Issue by wahspilihp** [amaxwell/tlutility#123]
Apple has added a (not very informative) deprecation warning to apps that call system python, and apparently will be removing it (rather than updating system python to 3.11).

**Comment by amaxwell** [comment]
Yes, Apple's douchey alert is a known problem, and will require either bundling a universal framework of Python with the application, or rewriting all of my Python code in Objective-C. So far I've failed at compiling Python as a universal framework.

I also haven't gotten far with the rewrite of the tlpdb parser. Frankly, it feels really stupid to waste my time rewriting code that's been working for years, just because the world's richest phone company is too lazy to include any updated UNIX tools.

**Comment by fxcoudert** [comment]
There is a python 3, but you have to call with as `python3`, not `python`:

```
$ /usr/bin/python3 -V
Python 3.8.9
```

**Comment by amaxwell** [comment]
> There is a python 3, but you have to call with as `python3`, not `python`:
> 
> ```
> $ /usr/bin/python3 -V
> Python 3.8.9
> ```

No, there isn't a python3 shipped with the OS, although there used to be. That is only is a stub that will prompt you to install the developer tools, which install a lobotomized Python.

> Python 2 will be removed in macOS 12.3 (it is removed in the beta version already), it has reached EOL anyway.

Yes, I know, and removing it in a minor update is a shitty thing to do, and a new low even for Apple.
