### ISSUE TITLE
TL Utility exited with error (Yosemite 10.10.5)

### ISSUE THREAD

**Issue by amunn** [amaxwell/tlutility#36]
Hi Adam, I just updated my distribution today and TL Utility exited with an error.  I've never encountered this before.  Full log attached.

[TLUtility-log.txt](https://github.com/amaxwell/tlutility/files/67557/TLUtility-log.txt)

**Comment by amaxwell** [comment]
Hi Alan, I really apologize for not following up on this when you posted it, but I just forgot. Did this only happen once? I vaguely recall a temporary problem due to misconfiguration of some font package(?) on the TeX Live side, which could explain the `*** ERROR *** exit status of pid = 36076 was 1` line. If I'm misreading this and TLU actually crashed, please let me know.

**Comment by amunn** [comment]
Hi Adam, no worries about not responding at the time. No, TLU didn't actually crash, so some TeX Live issue may indeed have been the source of the problem.  After this failure I just stopped updating for a while (I tend to update sporadically anyway). But my most recent update went without a hitch, so I'm assuming it was a transient thing. I mainly reported it to you in case the report was of some use.
Thanks for responding.
