### ISSUE TITLE
The "Reconfigure distributions..." script changes ownership of symlink to root

### ISSUE THREAD

**Issue by jfbu** [amaxwell/tlutility#40]
hi, the  `/Library/TeX/Distributions/.DefaultTeX/Contents` symlink is created with owner root when user switches distribution.

Not an issue for 99.9999% of users I guess, but I had a set-up not using root, and I noticed this behaviour when testing the TLU facility. I know that TLU handles fine TeXLive install to a repertory with user access, without forcing root ownership on created files.

Just for pointing out.

**Comment by amaxwell** [comment]
Thanks for checking, but this is expected behavior. Unless the user has manually mucked about with permissions on `/Library/TeX`, root is required to set up the symlink; I don't support setting up a symlink in the user domain (`~/Library/TeX`) at this time, and likely never will. This was mainly added because the TeX Distribution prefpane is broken for newer operating systems.
