### ISSUE TITLE
Can not build: "Code signing" error

### ISSUE THREAD

**Issue by jkarimi91** [amaxwell/tlutility#42]
![screen shot 2016-04-21 at 6 34 43 pm](https://cloud.githubusercontent.com/assets/8411317/14729135/c7d7023e-07ef-11e6-9981-757ee1ae880b.png)
 I receive several of these errors. I choose "fix issue" for each one, but the build still ends up failing

**Comment by amaxwell** [comment]
Create a self-signed certificate using Keychain Access and name it "TeX Live Utility Signing Certificate" (no quotes). See [Apple's documentation](https://developer.apple.com/library/mac/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html) for details. 

I codesign using a shell script build phase, since Apple has repeatedly failed to do it properly in Xcode. Hence, you may have to discard your changes if Xcode may have screwed up the project with its "fixing."
