### ISSUE TITLE
Problem running Tex Live Utility on a fresh Catalina

### ISSUE THREAD

**Issue by abuabara** [amaxwell/tlutility#78]
After updating a new computer to MacOS 10.15 (Catalina), and trying to run Tex Live Utility for the very first time on the system, I get the following message:
![Screen Shot 2019-11-16 at 3 30 44 PM](https://user-images.githubusercontent.com/12164393/68999481-4f761500-0886-11ea-9d10-f6413c186143.jpg)
Not sure why ... but I think it's because the spakle framework.
On systems that I had used the application before the OS update, it works flawlessly.
Any idea what it could be?
Thanks.

**Comment by amaxwell** [comment]
The possible solution I found via google is `xattr -rd com.apple.quarantine /path/to/TeX\ Live\ Utility.app` to remove the quarantine flag. You may also have to try control-clicking in Finder and choosing Open… if double-clicking complains about it being from an unidentified developer.

**Comment by abuabara** [comment]
Forgot to mention ... the control-clicking do not work (as usually work for other unidentified developer applications). But the `xattr` command worked perfectly!! I have been searching for it for a while and couldn't find any. Thanks a lot!!! Appreciate.

**Comment by BSVogler** [comment]
Mac OS: 10.15.2
TeX Live 1.35
When trying to launch the application I get the same message. I don't think that using some other undocumented command to open this application is a proper solution. It is workaround for developers.

**Comment by amaxwell** [comment]
Hi, Benny. Let me explain something, since you're once again trying to resurrect someone else's bug in lieu of actually providing any useful information about the problem you're seeing. You're quite right: using `xattr` is a workaround, and unfortunately that's what it will be until I decide it's worth buying a second hard drive to install Catalina and spending hours of my time in subservience to Apple's security theater du jour. I'm not risking my personal data with Apple's newer operating systems, and I see reason to pay Apple $100/year for the privilege of notarizing my software so that other people can use it.

Even if I decide that my time is worthless enough to do that, TeX Live Utility is still just a wrapper around a monstrous set of PERL scripts developed by the TeX Live Team. Further, if you installed via MacTeX, I'm helping you run those scripts as root, and **download later versions of them from the internet to run as root**. Apple's notarization/code signing/etc are, in this particular case, a false sense of security and a complete waste of everyone's time.

If you don't like the xattr workaround, I recommend that you run `tlmgr` in Terminal or wait until the next release of MacTeX. Alternately, pull the source from github and compile it yourself.

**Comment by BSVogler** [comment]
It is great that you feel responsible for this project, but as this is open source, other people might be interested in this issue (latest software is not running on the latest os) or even provide a fix. I am a developer with an apple developer membership so I could, in theory, sign it.
I noted an issue, in the process of creating a new ticket I saw that there is already a closed ticket for this. The actual issue is still not fixed and not documented. I think it would be great for the project to concentrate on creating usable software. For my personal use, I don't mind, as I think that I do not even need this tool.

**Comment by amaxwell** [comment]
It's fair to note that it's not documented, so I'll reopen this report.

**Comment by amaxwell** [comment]
Try this on Catalina and let me know what the result is (errors/warnings/anything). I've packaged it as a disk image, which may work more reliably with Gatekeeper, but I have no idea what you'll see. https://github.com/amaxwell/tlutility/releases/download/1.36b5/TeX.Live.Utility.app-1.36b5.dmg

**Comment by BSVogler** [comment]
The message now shows that this can not be opened because the system is unable to check for malware. I believe that this is the standard message for unsigned software. This warning can be surpassed by pressing command while right clicking on the app symbol and then using the open command. So this is an improvement.

**Comment by amaxwell** [comment]
I think this issue was actually fixed by repackaging in a .dmg last year. However, the next release will be notarized. A beta is available here: https://github.com/amaxwell/tlutility/releases/download/1.42b19/TeX.Live.Utility.app-1.42b19.dmg
