### ISSUE TITLE
Notarization?

### ISSUE THREAD

**Issue by defjaf** [amaxwell/tlutility#85]
Any chance of notarizing the software? This has come up since the lack of notarization means that it can’t be included in the latest MacteX distribution. 

(I see in https://github.com/amaxwell/tlutility/issues/78 that you indicate probably not—which is fine!—but I wanted to check explicitly...)

**Comment by amaxwell** [comment]
There's a chance, if my MacTeX friends can talk me into it, but I have some significant objections in principle and in practice. Honestly, I'm still hoping notarization goes away like some of Apple's other dumb fads (Objective-C garbage collection, for instance). My objection is currently threefold:

1. Since 2003, I have volunteered many hours of my life to write free software that people use (TLU and BibDesk). Anyone can help with that, and make sure it's as secure as possible, because the source is right here. All of this notarization stuff is to make users feel better, like the TSA seizing your nail clippers in the airport, and give Apple a way to remotely shut me down. I don't trust Apple, based on its arbitrary behavior with independent developers and App Store review, and I see notarization as a way to kill free software.

2. My rude answer in #78 aside, it's not worth it to me to spend $100 per year to maintain an official Apple developer account and signing certificate just so I can ship TLU with MacTeX. Sadly, I don't even use TeX anymore in my current work (and I also don't write Mac software professionally).

3. The Xcode required for this notarization business won't run on OS X High Sierra, my current system. I have no desire to install Mojave, let alone Catalina, on my personal computer just to build TLU: there is more stupid sandboxing, the UNIX and scripting layer are lobotomized, more older software won't work (QuickTime, for instance). Further, Apple now ships extremely buggy systems, and I no longer have an interest in risking my data by doing gratis QA for Apple (I was an official seed tester from 10.2-10.6.8, then dropped out after 10.7 because Apple was no longer responsive to my bug reports).

**Comment by defjaf** [comment]
Hi,  understood -- and thanks for both TLU and BibDesk!

**Comment by amaxwell** [comment]
You're welcome, and I appreciate your question. I expect it will come up pretty frequently in the next few weeks, as people install MacTeX, so I'd like to leave this open.

**Comment by srweintraub** [comment]
Thanks for the detailed reply, and definitely appreciate all your hard work! I don't use this software much except to knit Rmarkdown docs for work. I just updated MacTeX but it no longer has TeXLive, and now I can't seem to install it due to the issue noted above. This might be outside your scope, but do you know of a workaround, is there another way I can get the software needed (on Mac) to knit Markdown docs?

**Comment by amaxwell** [comment]
Hello @srweintraub, MacTeX *is* a full TeX Live, even though it no longer includes TeX Live Utility.

You can [download](http://amaxwell.github.io/tlutility/) and install TeX Live Utility manually, although you may have to control-click and choose "Open" in Finder to actually run it. If you installed BasicTeX, this might be what you're looking for to install additional packages.

**Comment by srweintraub** [comment]
Thank you so much!

**Comment by amaxwell** [comment]
The next release will be notarized. A beta is available here: https://github.com/amaxwell/tlutility/releases/download/1.42b19/TeX.Live.Utility.app-1.42b19.dmg
